(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ m[Kpython main-daniel.py
2022-06-21 17:34:43.096940: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:34:43.097252: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65420
 * Running on http://172.17.0.2:65420 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 17:34:48.553100: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:34:48.553162: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:34:52] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:34:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:34:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:34:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:34:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:34:53] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:35:12] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:35:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:35:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:35:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:35:30.360078: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:35:30.360570: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:36:15.409432: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:36:15.410591: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:36:59.595998: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:36:59.596041: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:37:17.996907: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:37:17.996959: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:37:28.656602: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:37:28.656679: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:37:45.841710: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:37:45.842157: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:38:31.211327: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:38:31.221324: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-21 17:39:08.850354: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:39:08.851556: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:39:31] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:39:32] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:39:32] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:39:32] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:40:01.324109: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:40:01.324159: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-21 17:40:48.273980: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:40:48.274527: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/ryland.py', reloading
 * Restarting with stat
2022-06-21 17:41:30.963169: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:41:30.963219: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:43:52.390165: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:43:52.391373: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:43:57] "[32mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420 HTTP/1.1[0m" 308 -
127.0.0.1 - - [21/Jun/2022 17:43:57] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1[0m" 500 -
127.0.0.1 - - [21/Jun/2022 17:43:57] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py", line 30, in home
    return render_template('index.html')
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/index.html", line 41, in top-level template code
    <li><a href="{{ url_for('/try') }}">Try It Out</a></li>
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/try'. Did you mean 'try_' instead?
127.0.0.1 - - [21/Jun/2022 17:43:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:43:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:43:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:43:58] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:08] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:44:09] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:09] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:09] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:09] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:09] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:12] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:44:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:44:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:44:30.625210: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:44:30.625716: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-21 17:44:54.157894: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:44:54.157935: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:44:58] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py", line 55, in try_
    return render_template(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/try.html", line 19, in top-level template code
    <li><a href="{{ url_for('index') }}">Home</a></li>
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'home' instead?
127.0.0.1 - - [21/Jun/2022 17:44:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:44:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:44:58] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:44:58] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:05] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:45:06] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:06] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:06] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:07] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:45:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:45:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:45:32.625851: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:45:32.627223: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:46:33.621047: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:46:33.621109: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py", line 42
    if ()
         ^
SyntaxError: invalid syntax
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python main-daniel.py
2022-06-21 17:56:09.385277: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:56:09.385337: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65420
 * Running on http://172.17.0.2:65420 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 17:56:14.850570: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:56:14.850637: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:56:20] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:56:20] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:20] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:20] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:33] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:56:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:33] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:47] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:56:47] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:47] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:56:47] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:57:12.089591: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:57:12.089653: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 17:57:21.814923: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:57:21.815605: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py', reloading
 * Restarting with stat
2022-06-21 17:57:51.449008: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:57:51.449644: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:58:10] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:58:11] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:11] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:11] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:29] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:58:29] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:29] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:29] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:55] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:58:56] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:56] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:56] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:56] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 17:58:56] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
^C(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python allisonMain.py
2022-06-21 17:59:48.413859: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:59:48.413923: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/


 * Serving Flask app 'allisonMain' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:7777
 * Running on http://172.17.0.2:7777 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 17:59:53.733835: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 17:59:53.733878: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 17:59:59] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py", line 46, in home
    return render_template('index.html', generated=None)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/index.html", line 23, in top-level template code
    <form action="{{ url_for('try_') }}" method="post">
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'try_'. Did you mean 'generate_text' instead?
127.0.0.1 - - [21/Jun/2022 17:59:59] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 17:59:59] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:00] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:00] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:00:04] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py", line 46, in home
    return render_template('index.html', generated=None)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/index.html", line 23, in top-level template code
    <form action="{{ url_for('try_') }}" method="post">
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'try_'. Did you mean 'generate_text' instead?
127.0.0.1 - - [21/Jun/2022 18:00:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:04] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:04] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:00:07] "[35m[1mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/ HTTP/1.1[0m" 500 -
Traceback (most recent call last):
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/allisonMain.py", line 46, in home
    return render_template('index.html', generated=None)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    return _render(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/templates/index.html", line 23, in top-level template code
    <form action="{{ url_for('try_') }}" method="post">
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 336, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/flask/helpers.py", line 323, in url_for
    rv = url_adapter.build(
  File "/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/miniconda3/lib/python3.9/site-packages/werkzeug/routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'try_'. Did you mean 'generate_text' instead?
127.0.0.1 - - [21/Jun/2022 18:00:07] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:08] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:08] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:00:08] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/7777/?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
^C^C^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ~[K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ~python allisonMain.pymain-daniel.py
2022-06-21 18:00:33.040817: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:00:33.041350: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65420
 * Running on http://172.17.0.2:65420 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 18:00:38.514369: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:00:38.514435: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-21 18:01:36.846615: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:01:36.846662: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-21 18:02:40.337123: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:02:40.337211: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:05:28.835850: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:05:28.835893: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:06:03.489446: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:06:03.490529: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:06:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:06:13] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:06:31.803911: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:06:31.804854: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:07:27.004230: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:07:27.005234: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:08:10.616115: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:08:10.633266: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:08:36.416773: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:08:36.423255: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:09:04.523154: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:09:04.523953: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:09:27.022307: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:09:27.023214: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:11:03.465318: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:11:03.466621: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:17:30.578721: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:17:30.582904: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:17:50.081744: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:17:50.082852: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:18:30] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:18:30] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:18:30] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:18:30] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:19:01] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:19:01] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:19:01] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:19:01] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:19:29.645882: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:19:29.647260: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:19:44.125530: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:19:44.125584: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
terminate called without an active exception
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ python main-daniel.py
2022-06-21 18:21:49.819068: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:21:49.829261: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65420
 * Running on http://172.17.0.2:65420 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 18:21:55.546642: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:21:55.546683: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:22:16] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:22:17] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:22:17] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:22:17] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:23:21.283511: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:23:21.283562: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:24:42] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:24:43] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:24:43] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:24:43] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:25:30] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:25:30] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:25:30] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:25:30] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:25:36.754201: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:25:36.755944: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:25:48] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:25:49] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:25:49] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:25:49] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
terminate called without an active exception
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ ^C
(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ [K(base) ]0;~/Anime-Description-Generator/app[01;34m~/Anime-Description-Generator/app[00m$ p
ython main-daniel.py
2022-06-21 18:29:28.813154: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:29:28.813249: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Serving Flask app 'main-daniel' (lazy loading)
 * Environment: production
[31m   WARNING: This is a development server. Do not use it in a production deployment.[0m
[2m   Use a production WSGI server instead.[0m
 * Debug mode: on
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:65420
 * Running on http://172.17.0.2:65420 (Press CTRL+C to quit)
 * Restarting with stat
2022-06-21 18:29:36.080252: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:29:36.080940: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:29:49] "POST /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/try HTTP/1.1" 200 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:30:03.584719: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:30:03.586077: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:30:15.728021: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:30:15.728357: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-21 18:30:38.024132: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:30:38.024437: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:30:48.800178: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:30:48.800554: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:33:34.566308: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:33:34.573693: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:33:52.309022: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:33:52.309390: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:36:15.346399: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:36:15.346718: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:37:54.762657: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:37:54.762704: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:39:32.408172: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:39:32.408449: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:39:58.165681: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:39:58.167716: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:43:37.286258: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:43:37.286300: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/


 * Debugger is active!
 * Debugger PIN: 109-457-385
127.0.0.1 - - [21/Jun/2022 18:43:51] "GET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/ HTTP/1.1" 200 -
127.0.0.1 - - [21/Jun/2022 18:43:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/main.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:43:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.css HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:43:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/index.js HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:43:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/aicamp.png HTTP/1.1[0m" 304 -
127.0.0.1 - - [21/Jun/2022 18:43:51] "[36mGET /ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65420/static/bg.jpg HTTP/1.1[0m" 304 -
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/main-daniel.py', reloading
 * Restarting with stat
2022-06-21 18:44:02.749299: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:44:02.757401: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
 * Detected change in '/projects/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/Anime-Description-Generator/app/raj.py', reloading
 * Restarting with stat
2022-06-21 18:44:25.376748: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-06-21 18:44:25.376797: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Try to open

    https://cocalc9.ai-camp.dev/ddfbcc4e-fb6a-46d3-a108-cd26783e2648/port/65421/


 * Debugger is active!
 * Debugger PIN: 109-457-385
